Test new function to analyse jacoco report

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -37,16 +37,14 @@ jobs:
         name: backend-coverage-report
         path: back/target/site/jacoco
 
-    - name: Download coverage report
-      uses: actions/download-artifact@v4
-      with:
-        name: backend-coverage-report
-        path: back/target/site/jacoco
-        
     - name: Check test coverage
       run: |
         COVERAGE_THRESHOLD=80
-        COVERAGE=$(grep -oP 'Total.*?(\d+\.\d+)%' back/target/site/jacoco/index.html | grep -oP '\d+\.\d+')
+        COVERAGE=$(mvn test jacoco:report | grep -oP 'Total.*?(\d+\.\d+)%' | awk '{print $2}' | cut -d'%' -f1)
+        if [ -z "$COVERAGE" ]; then
+          echo "Error: Failed to retrieve coverage percentage."
+          exit 1
+        fi
         echo "Detected coverage: $COVERAGE%"
         if [ $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc) -eq 1 ]; then
           echo "Coverage ($COVERAGE%) is below the threshold ($COVERAGE_THRESHOLD%)"
