Fix invalid file

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -89,16 +89,16 @@ jobs:
       run: npx sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=software-developer -Dsonar.projectKey=software-developer_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-Frontend -Dsonar.host.url=https://sonarcloud.io
 
     - name: Check Quality Gate status
-          run: |
-            STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
-              "https://sonarcloud.io/api/qualitygates/project_status?projectKey=software-developer_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-Frontend" \
-              | jq -r .projectStatus.status)
-            if [ "$STATUS" != "OK" ]; then
-              echo "Quality Gate failed: $STATUS"
-              exit 1
-            fi
-          env:
-            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=software-developer_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-Frontend" \
+          | jq -r .projectStatus.status)
+        if [ "$STATUS" != "OK" ]; then
+          echo "Quality Gate failed: $STATUS"
+          exit 1
+        fi
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   docker:
     runs-on: ubuntu-latest
     needs: test-and-coverage
